'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
import './website.css'
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY)
const money=n=>'¥'+Number(n||0).toLocaleString()
export default function Website(){
 const [events,setEvents]=useState([])
 useEffect(()=>{(async()=>{const {data}=await supabase.from('events').select('id,title,event_date,venue,open_time,start_time,advance_price,door_price,public_description,event_artists(sort_order,artists(name))').eq('website_published',true).order('event_date');setEvents(data||[])})()},[])
 return <div className="publicsite"><header className="sitehead"><a className="logo" href="/website">ThunderSnakeATSUGI</a><nav><a href="#schedule">SCHEDULE</a><a href="#access">ACCESS</a><a href="#about">ABOUT</a></nav></header><section className="hero"><p>LIVE MUSIC / EVERY NIGHT</p><h1>音楽が鳴る場所。</h1><span>ThunderSnakeATSUGIの最新イベント情報</span></section><main><section id="schedule"><div className="sectiontitle"><small>LIVE SCHEDULE</small><h2>SCHEDULE</h2></div><div className="schedule">{events.length?events.map(e=><article className="show" key={e.id}><div className="date"><b>{new Date(e.event_date+'T00:00:00').getDate()}</b><span>{new Date(e.event_date+'T00:00:00').toLocaleDateString('ja-JP',{year:'numeric',month:'short',weekday:'short'})}</span></div><div className="showbody"><h3>{e.title}</h3><p className="artists">{(e.event_artists||[]).sort((a,b)=>a.sort_order-b.sort_order).map(x=>x.artists?.name).filter(Boolean).join(' / ')||'出演者後日発表'}</p>{e.public_description&&<p>{e.public_description}</p>}<div className="meta"><span>OPEN {e.open_time?.slice(0,5)||'--:--'} / START {e.start_time?.slice(0,5)||'--:--'}</span><span>ADV {money(e.advance_price)} / DOOR {money(e.door_price)}</span><span>{e.venue||'ThunderSnakeATSUGI'}</span></div></div></article>):<p className="empty">公開予定のイベントはありません。</p>}</div></section><section id="about" className="info"><small>ABOUT</small><h2>厚木から、音楽を鳴らす。</h2><p>出演情報・公演スケジュールをこちらからご確認いただけます。</p></section><section id="access" className="info"><small>ACCESS</small><h2>ACCESS</h2><p>〒243-0014 神奈川県厚木市旭町1-22-20 ハラダ旭町ビル1F</p></section></main><footer>© ThunderSnakeATSUGI</footer></div>
}