'use client'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
import './website.css'
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY)
const money=n=>Number(n||0)>0?'¥'+Number(n).toLocaleString():'¥--'
const dow=['SUN','MON','TUE','WED','THU','FRI','SAT']
export default function Website(){
 const [events,setEvents]=useState([])
 const [news,setNews]=useState([])
 const [pickupIndex,setPickupIndex]=useState(0)
 const now=new Date()
 const [cursor,setCursor]=useState({y:now.getFullYear(),m:now.getMonth()+1})
 useEffect(()=>{(async()=>{const {data:n}=await supabase.from('website_news').select('id,title,category,body,published_at,created_at').eq('published',true).order('published_at',{ascending:false}).limit(3);setNews(n||[]);const {data}=await supabase.from('events').select('id,title,event_date,venue,open_time,start_time,advance_price,door_price,public_description,flyer_path,event_artists(sort_order,booking_status,artists(name,photo_path))').eq('website_published',true).order('event_date');setEvents(data||[])})()},[])
 const upcoming=useMemo(()=>events.filter(e=>e.event_date>=now.toISOString().slice(0,10)).slice(0,4),[events])
 const shown=events.filter(e=>{const d=new Date(e.event_date+'T00:00:00');return d.getFullYear()===cursor.y&&d.getMonth()+1===cursor.m})
 const move=n=>{const d=new Date(cursor.y,cursor.m-1+n,1);setCursor({y:d.getFullYear(),m:d.getMonth()+1})}
 const flyer=e=>e.flyer_path?supabase.storage.from('event-flyers').getPublicUrl(e.flyer_path).data.publicUrl:null
 const featured=upcoming[0]
 const featuredDate=featured?new Date(featured.event_date+'T00:00:00'):null
 return <div className="ts-site">
  <header className="ts-head"><a className="ts-logo" href="#top">THUNDER SNAKE <small>ATSUGI</small></a><nav><a href="#pickup">PICK UP</a><a href="#schedule">SCHEDULE</a><a href="#information">INFO</a><a href="#access">ACCESS</a></nav></header>
  <main>
   <section className="hero" id="top"><div className="hero-kicker">LIVE HOUSE / ATSUGI, KANAGAWA</div><h1><span>THUNDER</span><span>SNAKE</span><span className="hero-atsugi">ATSUGI</span></h1><div className="hero-bottom"></div></section>
   <section className="pickup" id="pickup"><div className="section-title"><span>01</span><h2>PICK UP</h2><p>UPCOMING EVENTS</p></div><div className="pickup-slider">{upcoming.length?<><div className="pickup-track" style={{transform:`translateX(-${pickupIndex*100}%)`}}>{upcoming.map((e,i)=>{const d=new Date(e.event_date+'T00:00:00');return <div className="pickup-slide" key={e.id}><a className="pickup-large" href={`/website/event/${e.id}`}><div className="pickup-large-image">{flyer(e)?<img src={flyer(e)} alt={e.title}/>:<div className="poster-type">THUNDER<br/>SNAKE</div>}<span className="pickup-no">0{i+1}</span></div><div className="pickup-large-copy"><time>{e.event_date.replaceAll('-','.')} / {dow[d.getDay()]}</time><h3>{e.title}</h3><p>OPEN {e.open_time?.slice(0,5)||'--:--'}　START {e.start_time?.slice(0,5)||'--:--'}<br/>ADV {money(e.advance_price)}　DOOR {money(e.door_price)}</p></div></a></div>})}</div><div className="pickup-controls"><button onClick={()=>setPickupIndex(i=>(i-1+upcoming.length)%upcoming.length)} aria-label="前のイベント">←</button><div className="pickup-progress"><span>{String(pickupIndex+1).padStart(2,'0')}</span><i></i><span>{String(upcoming.length).padStart(2,'0')}</span></div><button onClick={()=>setPickupIndex(i=>(i+1)%upcoming.length)} aria-label="次のイベント">→</button></div></>:<p className="empty">公開予定のイベントはありません。</p>}</div></section>
   <section className="schedule" id="schedule"><div className="section-title"><span>02</span><h2>SCHEDULE</h2><p>LIVE CALENDAR</p></div><div className="month-switch"><button onClick={()=>move(-1)} aria-label="前の月">←</button><div><span>{cursor.y}</span><strong>{String(cursor.m).padStart(2,'0')}</strong></div><button onClick={()=>move(1)} aria-label="次の月">→</button></div><div className="schedule-list">{shown.length?shown.map(e=>{const d=new Date(e.event_date+'T00:00:00');const artists=(e.event_artists||[]).filter(x=>x.booking_status==='確定'||!x.booking_status).sort((a,b)=>a.sort_order-b.sort_order).map(x=>x.artists?.name).filter(Boolean);return <a className="schedule-row" key={e.id} href={`/website/event/${e.id}`}><div className="date"><b>{String(d.getDate()).padStart(2,'0')}</b><span>{dow[d.getDay()]}</span></div><div className="thumb">{flyer(e)?<img src={flyer(e)} alt={e.title}/>:<span>TS</span>}</div><div className="event-info"><div className="schedule-label">LIVE EVENT</div><h3>{e.title}</h3>{artists.length>0&&<p className="artists">{artists.join(' / ')}</p>}<div className="schedule-meta"><p><span>OPEN / START</span>{e.open_time?.slice(0,5)||'--:--'} / {e.start_time?.slice(0,5)||'--:--'}</p><p><span>ADV / DOOR</span>{money(e.advance_price)} / {money(e.door_price)}</p></div></div><span className="arrow">↗</span></a>}):<div className="empty">この月の公開イベントはありません。</div>}</div></section>
   <section className="information" id="information"><div className="section-title"><span>03</span><h2>INFORMATION</h2><p>NEWS / NOTICE</p></div><div className="news-list">{news.length?news.map(n=>{const date=new Date(n.published_at||n.created_at).toLocaleDateString("ja-JP",{year:"numeric",month:"2-digit",day:"2-digit"}).replaceAll("/",".");return <article className="news-row" key={n.id}><div className="news-meta"><time>{date}</time><span>{n.category}</span></div><div className="news-copy"><h3>{n.title}</h3>{n.body&&<p>{n.body}</p>}</div><span className="news-arrow">↗</span></article>}):<div className="info-statement">LIVE MUSIC.<br/>NEW ENCOUNTERS.<br/>IN ATSUGI.</div>}</div></section>
   <section className="access" id="access"><div className="section-title"><span>04</span><h2>ACCESS</h2><p>COME SEE US</p></div><div className="access-layout"><div className="access-copy"><div className="access-index">THUNDER SNAKE / ATSUGI</div><h3>THUNDER<br/>SNAKE<br/><em>ATSUGI</em></h3><div className="access-details"><div><span>ADDRESS</span><p>〒243-0014<br/>神奈川県厚木市旭町1-22-20<br/>ハラダ旭町ビル1F</p></div><div><span>FROM STATION</span><p>小田急線 本厚木駅<br/>南口から徒歩圏内</p></div></div><a className="map-link" href="https://www.google.com/maps/search/?api=1&query=神奈川県厚木市旭町1-22-20" target="_blank" rel="noreferrer">OPEN IN GOOGLE MAPS <b>↗</b></a></div><div className="access-map"><iframe title="THUNDER SNAKE ATSUGI map" src="https://www.google.com/maps?q=神奈川県厚木市旭町1-22-20&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"></iframe><div className="map-caption"><span>ATSUGI / KANAGAWA</span><span>35.44° N</span></div></div></div></section>
  </main>
  <footer><div>THUNDER SNAKE <small>ATSUGI</small></div><p>© THUNDER SNAKE ATSUGI</p></footer>
 </div>
}