'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
const eventLabel={planning:'企画中',booking:'ブッキング中',confirmed:'確定',promoting:'告知中',show_day:'本番',ended:'終了'}, bookingLabel={offer:'オファー',waiting:'返答待ち',confirmed:'確定',declined:'辞退'};
const pad=n=>String(n).padStart(2,'0'), dateKey=(y,m,d)=>y+'-'+pad(m+1)+'-'+pad(d);
export default function Page(){
 const now=new Date(),[month,setMonth]=useState(new Date(now.getFullYear(),now.getMonth(),1)),[view,setView]=useState('calendar'),[session,setSession]=useState(null),[events,setEvents]=useState([]),[selected,setSelected]=useState(null),[artists,setArtists]=useState([]),[bookings,setBookings]=useState([]),[tasks,setTasks]=useState([]),[settlement,setSettlement]=useState(null),[modal,setModal]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true);
 const loadEvents=async()=>{const {data}=await supabase.from('events').select('*').order('event_date');setEvents(data||[]);setSelected(x=>x||data?.[0]||null)};
 const loadArtists=async()=>{const {data}=await supabase.from('artists').select('*').order('name');setArtists(data||[])};
 const loadEventData=async id=>{if(!id){setBookings([]);setTasks([]);setSettlement(null);return}const [{data:b},{data:t},{data:s}]=await Promise.all([supabase.from('event_artists').select('*,artists(*)').eq('event_id',id).order('performance_time'),supabase.from('tasks').select('*').eq('event_id',id).order('sort_order'),supabase.from('settlements').select('*').eq('event_id',id).maybeSingle()]);setBookings(b||[]);setTasks(t||[]);setSettlement(s||null)};
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false);if(data.session){loadEvents();loadArtists()}});const {data:s}=supabase.auth.onAuthStateChange((_e,x)=>{setSession(x);if(x){loadEvents();loadArtists()}});return()=>s.subscription.unsubscribe()},[]);
 useEffect(()=>{loadEventData(selected?.id)},[selected?.id]);
 const cells=useMemo(()=>{const y=month.getFullYear(),m=month.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,total=new Date(y,m+1,0).getDate();return Array.from({length:42},(_,i)=>{const d=i-first+1;return d>0&&d<=total?{d,key:dateKey(y,m,d)}:null})},[month]);
 const auth=async signup=>{const {error}=signup?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});setMessage(error?error.message:(signup?'登録しました。確認メールが届いた場合は確認してください。':'ログインしました。'))};
 const saveEvent=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),obj={title:f.get('title'),event_date:f.get('date'),status:f.get('status'),venue:f.get('venue')||null,open_time:f.get('open')||null,start_time:f.get('start')||null,advance_price:Number(f.get('advance')||0),door_price:Number(f.get('door')||0)};const q=modal==='edit'?supabase.from('events').update(obj).eq('id',selected.id).select().single():supabase.from('events').insert(obj).select().single();const {data,error}=await q;if(error)return alert(error.message);await loadEvents();setSelected(data);setModal('')};
 const addArtist=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.from('artists').insert({name:f.get('name'),contact_name:f.get('contact')||null,email:f.get('email')||null,phone:f.get('phone')||null});if(error)return alert(error.message);await loadArtists();setModal('')};
 const addBooking=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.from('event_artists').insert({event_id:selected.id,artist_id:f.get('artist'),booking_status:f.get('status'),performance_time:f.get('time')||null,guarantee:Number(f.get('guarantee')||0)});if(error)return alert(error.message);await loadEventData(selected.id);setModal('')};
 const addTask=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.from('tasks').insert({event_id:selected.id,title:f.get('title'),due_date:f.get('due')||null,sort_order:tasks.length});if(error)return alert(error.message);await loadEventData(selected.id);setModal('')};
 const saveMoney=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),obj={event_id:selected.id,ticket_sales:+f.get('ticket'),other_income:+f.get('income'),venue_cost:+f.get('venuecost'),production_cost:+f.get('production'),other_cost:+f.get('other')};const {error}=await supabase.from('settlements').upsert(obj,{onConflict:'event_id'});if(error)return alert(error.message);await loadEventData(selected.id);setModal('')};
 const toggleTask=async t=>{await supabase.from('tasks').update({completed:!t.completed}).eq('id',t.id);setTasks(x=>x.map(v=>v.id===t.id?{...v,completed:!v.completed}:v))};
 const delEvent=async()=>{if(!selected||!confirm('このイベントを削除しますか？'))return;const {error}=await supabase.from('events').delete().eq('id',selected.id);if(error)return alert(error.message);setEvents(x=>x.filter(e=>e.id!==selected.id));setSelected(null)};
 if(loading)return <div className="auth"><div className="authcard"><h2>読み込み中...</h2></div></div>;
 if(!session)return <div className="auth"><div className="authcard"><small>LIVE HOUSE</small><h1>EVENT MANAGER</h1><p>イベント制作・ブッキングをクラウドで管理</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="メールアドレス"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="パスワード"/><button className="primary" onClick={()=>auth(false)}>ログイン</button><button onClick={()=>auth(true)}>新規登録</button><p>{message}</p></div></div>;
 const nav=[['calendar','▣ カレンダー'],['events','☷ イベント一覧'],['artists','◉ アーティスト'],['tasks','☑ タスク'],['money','¥ 売上・精算']];
 const income=(settlement?.ticket_sales||0)+(settlement?.other_income||0),cost=(settlement?.venue_cost||0)+(settlement?.production_cost||0)+(settlement?.other_cost||0)+bookings.reduce((n,b)=>n+(b.guarantee||0),0);
 return <div className="shell"><aside><h1>LIVE HOUSE</h1><small>EVENT MANAGER</small>{nav.map(n=><button className={'nav '+(view===n[0]?'on':'')} onClick={()=>setView(n[0])} key={n[0]}>{n[1]}</button>)}<button className="signout" onClick={()=>supabase.auth.signOut()}>ログアウト</button></aside><main><header><div><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><h2>{month.getFullYear()}年{month.getMonth()+1}月</h2><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button><button onClick={()=>setMonth(new Date(now.getFullYear(),now.getMonth(),1))}>今日</button></div><button onClick={()=>setModal('artist')}>＋ アーティスト</button><button className="primary" onClick={()=>setModal('event')}>＋ 新規イベント</button></header>
 {view==='calendar'&&<section className="workspace"><div><div className="calendar"><div className="week">{['月','火','水','木','金','土','日'].map(x=><b key={x}>{x}</b>)}</div><div className="grid">{cells.map((c,i)=><div className="day" key={i}>{c&&<><span>{c.d}</span>{events.filter(e=>e.event_date===c.key).map(ev=><button key={ev.id} className={'event '+eventLabel[ev.status]} onClick={()=>setSelected(ev)}>{ev.title}<small>{eventLabel[ev.status]}</small></button>)}</>}</div>)}</div></div><div className="lower"><div className="card"><h3>制作タスク</h3>{tasks.slice(0,5).map(t=><label key={t.id}><input type="checkbox" checked={t.completed} onChange={()=>toggleTask(t)}/>{t.title}</label>)}{selected&&<button onClick={()=>setModal('task')}>＋ タスク追加</button>}</div><div className="card"><h3>今月の状況</h3><p>📅 イベント <b>{events.filter(e=>e.event_date.startsWith(month.getFullYear()+'-'+pad(month.getMonth()+1))).length}件</b></p><p>🎤 登録アーティスト <b>{artists.length}組</b></p></div></div></div><EventDetail selected={selected} bookings={bookings} tasks={tasks} settlement={settlement} income={income} cost={cost} setModal={setModal} toggleTask={toggleTask} delEvent={delEvent}/></section>}
 {view==='events'&&<div className="listpage"><h2>イベント一覧</h2>{events.map(e=><button className="listrow" key={e.id} onClick={()=>{setSelected(e);setView('calendar')}}><b>{e.event_date}</b><span>{e.title}</span><small>{eventLabel[e.status]}</small></button>)}</div>}
 {view==='artists'&&<div className="listpage"><div className="sectionhead"><h2>アーティスト</h2><button className="primary" onClick={()=>setModal('artist')}>＋ 登録</button></div>{artists.map(a=><div className="listrow" key={a.id}><b>{a.name}</b><span>{a.contact_name||'担当者未登録'}</span><small>{a.email||a.phone||''}</small></div>)}</div>}
 {view==='tasks'&&<div className="listpage"><h2>選択中イベントのタスク</h2>{tasks.map(t=><label className="listrow" key={t.id}><input type="checkbox" checked={t.completed} onChange={()=>toggleTask(t)}/><span>{t.title}</span><small>{t.due_date||''}</small></label>)}</div>}
 {view==='money'&&<div className="listpage"><h2>売上・精算</h2>{selected?<><h3>{selected.title}</h3><div className="moneycards"><div><small>売上</small><b>¥{income.toLocaleString()}</b></div><div><small>経費＋出演料</small><b>¥{cost.toLocaleString()}</b></div><div><small>収支</small><b>¥{(income-cost).toLocaleString()}</b></div></div><button className="primary" onClick={()=>setModal('money')}>精算を入力・編集</button></>:<p>イベントを選択してください。</p>}</div>}
 {modal&&<Modal type={modal} selected={selected} artists={artists} settlement={settlement} onClose={()=>setModal('')} saveEvent={saveEvent} addArtist={addArtist} addBooking={addBooking} addTask={addTask} saveMoney={saveMoney}/>}</main></div>}
function EventDetail({selected,bookings,tasks,settlement,income,cost,setModal,toggleTask,delEvent}){return <div className="detail">{selected?<><div className="sectionhead"><h2>{selected.event_date}<br/>{selected.title}</h2><button onClick={()=>setModal('edit')}>編集</button></div><span className="pill">{eventLabel[selected.status]}</span><p>◷ OPEN {selected.open_time?.slice(0,5)||'--:--'} / START {selected.start_time?.slice(0,5)||'--:--'}</p><p>⌖ {selected.venue||'会場未設定'}</p><p>¥ 前売 ¥{Number(selected.advance_price||0).toLocaleString()} / 当日 ¥{Number(selected.door_price||0).toLocaleString()}</p><hr/><div className="sectionhead"><h3>出演者・ブッキング</h3><button onClick={()=>setModal('booking')}>＋ 追加</button></div>{bookings.map(b=><div className="booking" key={b.id}><b>{b.artists?.name}</b><span>{bookingLabel[b.booking_status]}</span><small>{b.performance_time?.slice(0,5)||'時間未定'}</small><strong>¥{Number(b.guarantee||0).toLocaleString()}</strong></div>)}<hr/><h3>制作進行</h3>{tasks.map(t=><label key={t.id}><input type="checkbox" checked={t.completed} onChange={()=>toggleTask(t)}/>{t.title}</label>)}<hr/><h3>精算</h3><p>売上 ¥{income.toLocaleString()} / 経費等 ¥{cost.toLocaleString()}</p><button onClick={()=>setModal('money')}>精算編集</button><button className="danger" onClick={delEvent}>イベントを削除</button></>:<p>イベントを選択してください。</p>}</div>}
function Modal({type,selected,artists,settlement,onClose,saveEvent,addArtist,addBooking,addTask,saveMoney}){const submit=type==='event'||type==='edit'?saveEvent:type==='artist'?addArtist:type==='booking'?addBooking:type==='money'?saveMoney:addTask;return <div className="modal"><form onSubmit={submit}><h2>{type==='event'?'新規イベント':type==='edit'?'イベント編集':type==='artist'?'アーティスト登録':type==='booking'?'出演者追加':type==='money'?'売上・精算':'タスク追加'}</h2>{(type==='event'||type==='edit')&&<><input name="title" defaultValue={type==='edit'?selected?.title:''} placeholder="イベント名" required/><input name="date" type="date" defaultValue={type==='edit'?selected?.event_date:''} required/><select name="status" defaultValue={type==='edit'?selected?.status:'booking'}>{Object.entries(eventLabel).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><input name="venue" defaultValue={type==='edit'?selected?.venue||'':''} placeholder="会場"/><div className="twocol"><input name="open" type="time" defaultValue={type==='edit'?selected?.open_time?.slice(0,5)||'':''}/><input name="start" type="time" defaultValue={type==='edit'?selected?.start_time?.slice(0,5)||'':''}/></div><div className="twocol"><input name="advance" type="number" min="0" defaultValue={type==='edit'?selected?.advance_price||0:0} placeholder="前売"/><input name="door" type="number" min="0" defaultValue={type==='edit'?selected?.door_price||0:0} placeholder="当日"/></div></>}{type==='artist'&&<><input name="name" placeholder="アーティスト名" required/><input name="contact" placeholder="担当者"/><input name="email" type="email" placeholder="メール"/><input name="phone" placeholder="電話"/></>}{type==='booking'&&<><select name="artist" required><option value="">アーティストを選択</option>{artists.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select><select name="status">{Object.entries(bookingLabel).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><input name="time" type="time"/><input name="guarantee" type="number" min="0" placeholder="ギャラ"/></>}{type==='task'&&<><input name="title" placeholder="タスク名" required/><input name="due" type="date"/></>}{type==='money'&&<><input name="ticket" type="number" min="0" defaultValue={settlement?.ticket_sales||0} placeholder="チケット売上"/><input name="income" type="number" min="0" defaultValue={settlement?.other_income||0} placeholder="その他売上"/><input name="venuecost" type="number" min="0" defaultValue={settlement?.venue_cost||0} placeholder="会場費"/><input name="production" type="number" min="0" defaultValue={settlement?.production_cost||0} placeholder="制作費"/><input name="other" type="number" min="0" defaultValue={settlement?.other_cost||0} placeholder="その他経費"/></>}<div><button type="button" onClick={onClose}>キャンセル</button><button className="primary">保存</button></div></form></div>}
