'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {createClient} from '@supabase/supabase-js'
import './website-admin.css'
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY)
export default function WebsiteAdmin(){
 const [team,setTeam]=useState(null),[items,setItems]=useState([]),[editing,setEditing]=useState(null),[loading,setLoading]=useState(true)
 const load=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/';return}const {data:m}=await supabase.from('team_members').select('team_id,teams(name)').eq('user_id',user.id).limit(1).maybeSingle();if(!m){setLoading(false);return}setTeam(m);const {data}=await supabase.from('website_news').select('*').eq('team_id',m.team_id).order('created_at',{ascending:false});setItems(data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const save=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),published=f.get('published')==='on';const obj={team_id:team.team_id,title:f.get('title'),category:f.get('category')||'NEWS',body:f.get('body')||'',published,published_at:published?(editing?.published_at||new Date().toISOString()):null,updated_at:new Date().toISOString()};const {error}=editing?await supabase.from('website_news').update(obj).eq('id',editing.id):await supabase.from('website_news').insert(obj);if(error)return alert(error.message);setEditing(null);e.currentTarget.reset();await load()}
 const remove=async x=>{if(!confirm('「'+x.title+'」を削除しますか？'))return;const {error}=await supabase.from('website_news').delete().eq('id',x.id);if(error)return alert(error.message);await load()}
 if(loading)return <div className="webadmin-state">読み込み中...</div>
 return <main className="webadmin"><header><div><small>THUNDER SNAKE ATSUGI</small><h1>WEBSITE<br/>INFORMATION</h1></div><div><Link href="/">← 管理画面</Link><Link href="/website" target="_blank">サイトを見る ↗</Link></div></header><section className="webadmin-grid"><form onSubmit={save} key={editing?.id||'new'}><div className="form-kicker">{editing?'EDIT INFORMATION':'NEW INFORMATION'}</div><label>CATEGORY<select name="category" defaultValue={editing?.category||'NEWS'}><option>NEWS</option><option>EVENT</option><option>NOTICE</option><option>RECRUIT</option><option>VENUE</option></select></label><label>TITLE<input name="title" required maxLength="200" defaultValue={editing?.title||''}/></label><label>BODY<textarea name="body" rows="9" defaultValue={editing?.body||''}/></label><label className="publish-check"><input type="checkbox" name="published" defaultChecked={editing?.published||false}/> サイトに公開する</label><button className="save-news" type="submit">{editing?'UPDATE':'PUBLISH / SAVE'}</button>{editing&&<button type="button" className="cancel-news" onClick={()=>setEditing(null)}>キャンセル</button>}</form><div className="webadmin-list"><div className="form-kicker">INFORMATION LIST / {String(items.length).padStart(2,'0')}</div>{items.length?items.map(x=><article key={x.id}><div><span>{x.category}</span><time>{new Date(x.published_at||x.created_at).toLocaleDateString('ja-JP')}</time></div><h2>{x.title}</h2><p>{x.body}</p><footer><b className={x.published?'published':'draft'}>{x.published?'PUBLISHED':'DRAFT'}</b><div><button onClick={()=>setEditing(x)}>編集</button><button onClick={()=>remove(x)}>削除</button></div></footer></article>):<p>お知らせはまだありません。</p>}</div></section></main>
}